name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: actions/setup-python@v1
      - run: npm ci
      - run: npm run all
      - run: pip install markdown-to-presentation
      - run: markdown-to-presentation push --pages-branch release README.md LICENSE action.yml dist/index.js
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
